name: IMG Magisk Patcher

on:
  workflow_dispatch:
    inputs:
      URL:
        required: true
        default: 'https://github.com/Tonyha7/actions_android_ota_magisk_patcher/releases/download/4781008599/new-boot.img'
      MAGISK:
        required: true
        default: 'https://github.com/topjohnwu/Magisk/releases/download/v26.1/Magisk-v26.1.apk'
      PATCH_PARTITION:
        required: true
        default: 'boot'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Download Magisk & Patch
        run: |
          sudo apt install -y rename
          mkdir magisk
          cd magisk
          wget "${{ github.event.inputs.URL }}" -O ${{ github.event.inputs.PATCH_PARTITION }}.img
          wget "${{ github.event.inputs.MAGISK }}" -O Magisk.zip
          unzip Magisk.zip >> /dev/null
          cd ./lib/x86_64
          rename 's/(lib|\.so)//g' *
          cd ../../
          mv ./lib/x86_64/* ./assets
          chmod -R a+x ./assets/*
          cd assets
          bash ./boot_patch.sh ../${{ github.event.inputs.PATCH_PARTITION }}.img

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: | 
            magisk/assets/*.img
          name: Magisk_Patched_${{ github.run_id }}
          tag_name: ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
